modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
    modId="penguinlib"
    version="${file.jarVersion}"
    displayName="Penguin Lib"
    authors="joshiejack"
    description='''Booya'''
[[dependencies.penguinlib]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.penguinlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"